[package]
name = "eziter"
version = "0.1.0"
edition = "2021"
description = "Wrapper around Iterator"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.7"
